#!/usr/bin/env bash
set -euo pipefail

MODE="default"
if [[ $# -gt 0 ]]; then
  MODE="$1"
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="${ROOT_DIR}/docker-compose.dev.yml"
ENV_FILE="${ROOT_DIR}/.env.development"
DOCKER_COMPOSE_CMD=()

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "[setup-env] Missing required command: $1" >&2
    exit 1
  fi
}

resolve_compose() {
  if docker compose version >/dev/null 2>&1; then
    DOCKER_COMPOSE_CMD=(docker compose)
  elif command -v docker-compose >/dev/null 2>&1; then
    DOCKER_COMPOSE_CMD=(docker-compose)
  else
    echo "[setup-env] docker compose plugin or docker-compose is required" >&2
    exit 1
  fi
}

docker_compose() {
  if [[ ${#DOCKER_COMPOSE_CMD[@]} -eq 0 ]]; then
    resolve_compose
  fi
  "${DOCKER_COMPOSE_CMD[@]}" -f "$COMPOSE_FILE" "$@"
}

wait_for_postgres() {
  echo "[setup-env] Waiting for Postgres..."
  for _ in $(seq 1 60); do
    if docker_compose exec -T postgres pg_isready -U goosed -d goosed >/dev/null 2>&1; then
      echo "[setup-env] Postgres is ready."
      return 0
    fi
    sleep 2
  done
  echo "[setup-env] Timed out waiting for Postgres" >&2
  return 1
}

wait_for_nats_endpoint() {
  local description="$1"
  local path="$2"
  local display_url="http://localhost:8222${path}"
  local container_url="http://127.0.0.1:8222${path}"

  echo "[setup-env] Waiting for ${description} (${display_url})..."
  for _ in $(seq 1 60); do
    if docker_compose exec -T nats wget -qO- "$container_url" >/dev/null 2>&1; then
      echo "[setup-env] ${description} is reachable."
      return 0
    fi
    sleep 2
  done

  echo "[setup-env] Timed out waiting for ${description} at ${display_url}" >&2
  return 1
}

wait_for_seaweed_endpoint() {
  local description="$1"
  local path="$2"
  local display_url="http://localhost:9333${path}"
  local container_url="http://127.0.0.1:9333${path}"

  echo "[setup-env] Waiting for ${description} (${display_url})..."
  for _ in $(seq 1 60); do
    if docker_compose exec -T seaweedfs wget -qO- "$container_url" >/dev/null 2>&1; then
      echo "[setup-env] ${description} is reachable."
      return 0
    fi
    sleep 2
  done

  echo "[setup-env] Timed out waiting for ${description} at ${display_url}" >&2
  return 1
}

bootstrap_env_file() {
  if [[ -f "$ENV_FILE" ]]; then
    return
  fi

  cat <<EOT >"$ENV_FILE"
# Generated by setup-env.sh
DB_DSN=postgres://goosed:goosed@localhost:5432/goosed?sslmode=disable
NATS_URL=nats://localhost:4222
S3_ENDPOINT=http://localhost:8333
S3_REGION=us-east-1
S3_ACCESS_KEY=goosed
S3_SECRET_KEY=goosedsecret
S3_DISABLE_TLS=true
EOT

  echo "[setup-env] Wrote ${ENV_FILE} with default development credentials."
}

main() {
  require_cmd docker
  require_cmd go

  case "$MODE" in
    pull-only|--pull-only)
      MODE="pull-only"
      ;;
  esac

  if [[ ! -f "$COMPOSE_FILE" ]]; then
    echo "[setup-env] Missing ${COMPOSE_FILE}." >&2
    exit 1
  fi

  echo "[setup-env] Pulling container images..."
  docker_compose pull

  if [[ "$MODE" != "pull-only" ]]; then
    echo "[setup-env] Starting development stack..."
    docker_compose up -d

    wait_for_postgres
    wait_for_nats_endpoint "NATS" "/healthz"
    wait_for_nats_endpoint "NATS JetStream" "/jsz"
    wait_for_seaweed_endpoint "SeaweedFS" "/cluster/status"
  fi

  bootstrap_env_file

  echo "[setup-env] Downloading Go modules..."
  (cd "$ROOT_DIR" && go mod download)

  cat <<'INFO'
[setup-env] Development environment ready.

Export these environment variables (or source .env.development):
  source .env.development

Services:
  Postgres 17  -> localhost:5432 (user: goosed, password: goosed, db: goosed)
  NATS JS     -> localhost:4222 (monitoring: http://localhost:8222)
  SeaweedFS   -> S3 http://localhost:8333 (access: goosed / goosedsecret)
INFO
}

main "$@"
